
CREATE TYPE "e_vibe" AS ENUM ('1', '2', '3', '4', '5');


CREATE TYPE "e_role" AS ENUM ('super_admin', 'admin', 'regular');


CREATE TABLE "user_account" (
        "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "firstname" varchar(50),
        "lastname" varchar(50),
        "email" varchar(100),
        "password_hash" varchar(200),
        "role" e_role,
        "created_at" timestamp,
                                                                                                                                           "edited_at" timestamp);


CREATE TABLE "workout" (
        "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" int, "name" varchar(100) NOT NULL,
        "info" varchar(500) NOT NULL,
        "created_at" timestamp);


CREATE TABLE "move" (
        "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" int, "name" varchar(100) NOT NULL,
        "info" varchar(500) NOT NULL,
        "created_at" timestamp);


CREATE TABLE "workout_moves" (
        "workout_id" int, "move_id" int, "added_at" timestamp,
        PRIMARY KEY ("workout_id", "move_id"));


CREATE TABLE "workout_executions" (
        "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "workout_id" int, "info" varchar(1000) NOT NULL,
        "created_at" timestamp,
        "ended_at" timestamp);


CREATE TABLE "move_execution" (
        "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "workout_execution_id" int, "move_id" int, "sets" int NOT NULL,
        "reps" int NOT NULL,
        "weight" float NOT NULL,
        "vibe" e_vibe NOT NULL,
        "resting_time" int,
        "info" varchar(1000),
        "created_at" timestamp);


ALTER TABLE "workout" ADD
FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");


ALTER TABLE "move" ADD
FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");


ALTER TABLE "workout_moves" ADD
FOREIGN KEY ("workout_id") REFERENCES "workout" ("id");


ALTER TABLE "workout_moves" ADD
FOREIGN KEY ("move_id") REFERENCES "move" ("id");


ALTER TABLE "workout_executions" ADD
FOREIGN KEY ("workout_id") REFERENCES "workout" ("id");


ALTER TABLE "move_execution" ADD
FOREIGN KEY ("workout_execution_id") REFERENCES "workout_executions" ("id");


ALTER TABLE "move_execution" ADD
FOREIGN KEY ("move_id") REFERENCES "move" ("id");

